# -*- coding: utf-8 -*-
"""helmet_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1XyDpwOh7w2eFgDAobeAoGp67eAsOCL
"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/helmet_project/Helmet - No helmet detection.v1.yolov8.zip"

import os

print(os.listdir('/content/drive/MyDrive'))

import zipfile

zip_path = "/content/drive/MyDrive/helmet_project/Helmet - No helmet detection.v1i.yolov8.zip"
extract_path = "/content/helmet_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

print(os.listdir('/content/helmet_dataset'))

import os

print(os.listdir('/content/helmet_dataset/train'))

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.train(
    data='/content/helmet_dataset/data.yaml',
    epochs=50,
    imgsz=640
)

import os

print(os.listdir('/content/runs/detect'))

import os

print(os.listdir('/content/runs/detect/helmet_yolov8n_fixed/weights'))

import os

folders = os.listdir('/content/runs/detect')

for f in folders:
    path = f'/content/runs/detect/{f}/weights'
    if os.path.exists(path):
        print(f, "→", os.listdir(path))

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train2/weights/best.pt')

model.predict(
    source='/content/helmet_dataset/test/images',
    save=True
)

from ultralytics import YOLO

# Load the trained model
model = YOLO('/content/runs/detect/train2/weights/best.pt')

# Validate the model
metrics = model.val(
    data='/content/helmet_dataset/data.yaml',
    imgsz=640
)

# Print evaluation metrics
print("mAP50-95:", metrics.box.map)
print("mAP50:", metrics.box.map50)
print("mAP75:", metrics.box.map75)
print("Precision:", metrics.box.p)
print("Recall:", metrics.box.r)

import glob
from IPython.display import Image, display

imgs = glob.glob('/content/runs/detect/predict/*.jpg')[:5]

for img in imgs:
    display(Image(filename=img))

!pip install opencv-python

from IPython.display import display, Javascript
from google.colab.output import eval_js
import cv2
import numpy as np
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');
            const capture = document.createElement('button');
            capture.textContent = 'Capture';
            div.appendChild(capture);

            const video = document.createElement('video');
            video.style.display = 'block';
            const stream = await navigator.mediaDevices.getUserMedia({video: true});

            document.body.appendChild(div);
            div.appendChild(video);
            video.srcObject = stream;
            await video.play();

            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

            await new Promise((resolve) => capture.onclick = resolve);

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);

            stream.getTracks().forEach(track => track.stop());
            div.remove();

            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])

    with open(filename, 'wb') as f:
        f.write(binary)

    return filename

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train2/weights/best.pt')

from google.colab import files
files.download('/content/runs/detect/train2/weights/best.pt')

import os

train_imgs = len(os.listdir('/content/helmet_dataset/train/images'))
val_imgs = len(os.listdir('/content/helmet_dataset/valid/images'))
test_imgs = len(os.listdir('/content/helmet_dataset/test/images'))

print("Train:", train_imgs)
print("Validation:", val_imgs)
print("Test:", test_imgs)

import zipfile

zip_path = "/content/drive/MyDrive/helmet_project/Indian License Plate.v1-v1.yolov8.zip"
extract_path = "/content/plate_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

print(os.listdir('/content/plate_dataset'))

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.train(
    data='/content/plate_dataset/data.yaml',
    epochs=50,
    imgsz=640
)

import glob

paths = glob.glob('/content/runs/detect/*/weights/best.pt')

for p in paths:
    print(p)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/helmet_yolov8n/weights/best.pt')

import os
print(os.path.exists('/content/runs/detect/helmet_yolov8n/weights/best.pt'))

from google.colab import files
files.download('/content/runs/detect/helmet_yolov8n/weights/best.pt')

data='/content/plate_dataset/data.yaml'

import os

train = len(os.listdir('/content/helmet_dataset/train/images'))
val = len(os.listdir('/content/helmet_dataset/valid/images'))
test = len(os.listdir('/content/helmet_dataset/test/images'))

print("Train:", train)
print("Validation:", val)
print("Test:", test)
print("Total:", train + val + test)

import csv
from datetime import datetime

import os

import csv

import os
import csv

file_name = "plate_data.csv"

if not os.path.exists(file_name):
    with open(file_name, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Plate Number", "Time", "Image"])

import os
import csv
from datetime import datetime

file_name = "plate_data.csv"

if not os.path.exists(file_name):
    with open(file_name, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Plate Number", "Time", "Image"])