# -*- coding: utf-8 -*-
"""helmet_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1XyDpwOh7w2eFgDAobeAoGp67eAsOCL
"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/helmet_project/Helmet - No helmet detection.v1.yolov8.zip"

import os

print(os.listdir('/content/drive/MyDrive'))

import zipfile

zip_path = "/content/drive/MyDrive/helmet_project/Helmet - No helmet detection.v1i.yolov8.zip"
extract_path = "/content/helmet_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

print(os.listdir('/content/helmet_dataset'))

import os

print(os.listdir('/content/helmet_dataset/train'))

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.train(
    data='/content/helmet_dataset/data.yaml',
    epochs=50,
    imgsz=640
)

import zipfile
import os

zip_path = "/content/drive/MyDrive/helmet_project/Indian License Plate.v1-v1.yolov8.zip"
extract_path = "/content/numberplate_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted!")

import yaml

yaml_path = "/content/numberplate_dataset/data.yaml"

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

data['train'] = '/content/numberplate_dataset/train/images'
data['val'] = '/content/numberplate_dataset/valid/images'
data['test'] = '/content/numberplate_dataset/test/images'

with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

print("YAML file updated!")

!cat /content/numberplate_dataset/data.yaml

from ultralytics import YOLO

model = YOLO('yolov8s.pt')   # recommended for better accuracy

model.train(
    data='/content/numberplate_dataset/data.yaml',
    epochs=50,
    imgsz=640,
    batch=16,
    name='numberplate_model'
)

model = YOLO('/content/runs/detect/numberplate_model/weights/best.pt')

results = model('/content/numberplate_dataset/test/images', save=True)

import os

train_path = "/content/numberplate_dataset/train/images"
val_path = "/content/numberplate_dataset/valid/images"
test_path = "/content/numberplate_dataset/test/images"

train_count = len(os.listdir(train_path))
val_count = len(os.listdir(val_path))
test_count = len(os.listdir(test_path))

print("Train Images:", train_count)
print("Validation Images:", val_count)
print("Test Images:", test_count)

print("Total Images:", train_count + val_count + test_count)

from google.colab import files
uploaded = files.upload()

import os

print(os.listdir('runs/detect'))

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# Correct paths
helmet_model = YOLO('runs/detect/train/weights/best.pt')
plate_model = YOLO('runs/detect/numberplate_model/weights/best.pt')

frame = cv2.imread('test1.png')  # fix extension also

helmet_results = helmet_model(frame)[0]
plate_results = plate_model(frame)[0]

cv2_imshow(frame)

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# Correct paths
helmet_model = YOLO('runs/detect/train/weights/best.pt')
plate_model = YOLO('runs/detect/numberplate_model/weights/best.pt')

frame = cv2.imread('test2.png')  # fix extension also

helmet_results = helmet_model(frame)[0]
plate_results = plate_model(frame)[0]

cv2_imshow(frame)

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# Correct paths
helmet_model = YOLO('runs/detect/train/weights/best.pt')
plate_model = YOLO('runs/detect/numberplate_model/weights/best.pt')

frame = cv2.imread('test3.png')  # fix extension also

helmet_results = helmet_model(frame)[0]
plate_results = plate_model(frame)[0]

cv2_imshow(frame)

!pip install easyocr

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow
import easyocr

# Load models
helmet_model = YOLO('runs/detect/train/weights/best.pt')
plate_model = YOLO('runs/detect/numberplate_model/weights/best.pt')

# OCR
reader = easyocr.Reader(['en'])

# Load image
frame = cv2.imread('test4.png')

helmet_results = helmet_model(frame)[0]

for box in helmet_results.boxes:
    x1, y1, x2, y2 = map(int, box.xyxy[0])
    cls = int(box.cls[0])
    label = helmet_model.names[cls]

    # Draw helmet box
    cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,0), 2)
    cv2.putText(frame, label, (x1,y1-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

    # -------- IF NO HELMET --------
    if label == "Face and Hairs":   # FIXED

        rider_crop = frame[y1:y2, x1:x2]

        plate_results = plate_model(rider_crop)[0]

        for pbox in plate_results.boxes:
            px1, py1, px2, py2 = map(int, pbox.xyxy[0])

            plate_crop = rider_crop[py1:py2, px1:px2]

            # 🔥 Improve OCR accuracy
            plate_crop = cv2.resize(plate_crop, None, fx=2, fy=2)
            gray = cv2.cvtColor(plate_crop, cv2.COLOR_BGR2GRAY)

            # Draw plate box
            cv2.rectangle(frame,
                          (x1+px1, y1+py1),
                          (x1+px2, y1+py2),
                          (0,0,255), 2)

            # -------- OCR --------
            ocr_result = reader.readtext(gray)

            for res in ocr_result:
                text = res[1]

                print("Plate:", text)

                cv2.putText(frame, text, (x1, y2+30),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,0,255), 2)

# Show final output
cv2_imshow(frame)

from ultralytics import YOLO
import cv2
from google.colab.patches import cv2_imshow

# Correct paths
helmet_model = YOLO('runs/detect/train/weights/best.pt')
plate_model = YOLO('runs/detect/numberplate_model/weights/best.pt')

frame = cv2.imread('test4.png')  # fix extension also

helmet_results = helmet_model(frame)[0]
plate_results = plate_model(frame)[0]

cv2_imshow(frame)

!cp runs/detect/train/weights/best.pt helmet_best.pt
!cp runs/detect/numberplate_model/weights/best.pt numberplate_best.pt

from google.colab import files

files.download('helmet_best.pt')
files.download('numberplate_best.pt')